name: "Filesize Guard"
description: "Blocks pull requests with unintentionally oversized files"
author: "Chris Rutkowski"
inputs:
  ignore_file:
    description: "Path to the ignore file"
    required: true
    default: "./filesize_guard.ignore"
  max_size_kb:
    description: "Maximum allowed file size in kB"
    required: true
    default: "100"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        json: true
        write_output_files: true
        safe_output: false

    - name: Run Filesize Guard
      run: |
        python3 ${GITHUB_ACTION_PATH}/filesize_guard.py ${{ inputs.ignore_file }} ${{ inputs.max_size_kb }} .github/outputs/modified_files.json .github/outputs/added_files.json
      shell: bash
